autos = [
    {"merk": "Volkswagen", "model": "Golf", "motor_inhoud": 2000},
    {"merk": "Toyota", "model": "Corolla", "motor_inhoud": 2000},
    {"merk": "Ford", "model": "Focus", "motor_inhoud": 2000},
    {"merk": "BMW", "model": "3 Serie", "motor_inhoud": 2000},
    {"merk": "Audi", "model": "A4", "motor_inhoud": 2000},
    {"merk": "Mercedes-Benz", "model": "C-Klasse", "motor_inhoud": 2000},
    {"merk": "Honda", "model": "Civic", "motor_inhoud": 2000},
    {"merk": "Hyundai", "model": "Elantra", "motor_inhoud": 2000},
    {"merk": "Mazda", "model": "3", "motor_inhoud": 2000},
    {"merk": "Nissan", "model": "Sentra", "motor_inhoud": 2000},
    {"merk": "Chevrolet", "model": "Cruze", "motor_inhoud": 1000},
    {"merk": "Subaru", "model": "Impreza", "motor_inhoud": 2000},
    {"merk": "Kia", "model": "Forte", "motor_inhoud": 2000},
    {"merk": "Peugeot", "model": "308", "motor_inhoud": 2000},
    {"merk": "Renault", "model": "Megane", "motor_inhoud": 2000},
    {"merk": "Fiat", "model": "Tipo", "motor_inhoud": 1400},
    {"merk": "Opel", "model": "Astra", "motor_inhoud": 1600},
    {"merk": "Skoda", "model": "Octavia", "motor_inhoud": 2000},
    {"merk": "Volvo", "model": "S60", "motor_inhoud": 2000},
    {"merk": "Jaguar", "model": "XE", "motor_inhoud": 2000},
    {"merk": "Lexus", "model": "IS", "motor_inhoud": 2000},
    {"merk": "Infiniti", "model": "Q50", "motor_inhoud": 2000},
    {"merk": "Mitsubishi", "model": "Lancer", "motor_inhoud": 2000},
    {"merk": "Seat", "model": "Leon", "motor_inhoud": 2000}
]